services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-auth-${CONFIG_NAME}
    restart: always
    ports:
      - "${RABBIT_PORT}:5672"     
      - "${RABBIT_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      auth_network:
        aliases:
          - rabbitmq-auth-${CONFIG_NAME}
  
  redis:
    image: redis:7-alpine
    container_name: redis-auth-${CONFIG_NAME}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"    
    networks:
      auth_network:
        aliases:
          - redis-auth-${CONFIG_NAME}

  web:
    image: ${DOCKERHUB_USERNAME}/auth-service:${TAG}
    container_name: auth-service-${CONFIG_NAME}
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - auth_network

networks:
  auth_network:
    external: true
